// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockFile(arg1) {
  return window['go']['main']['App']['BlockFile'](arg1);
}

export function BlockFiles(arg1) {
  return window['go']['main']['App']['BlockFiles'](arg1);
}

export function BlockInstalledApp(arg1) {
  return window['go']['main']['App']['BlockInstalledApp'](arg1);
}

export function GetBlockedApps() {
  return window['go']['main']['App']['GetBlockedApps']();
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function RefreshApps() {
  return window['go']['main']['App']['RefreshApps']();
}

export function UnblockFile(arg1) {
  return window['go']['main']['App']['UnblockFile'](arg1);
}

export function UnblockFiles(arg1) {
  return window['go']['main']['App']['UnblockFiles'](arg1);
}

export function UnblockInstalledApp(arg1) {
  return window['go']['main']['App']['UnblockInstalledApp'](arg1);
}
