// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apps} from '../models';
import {firewall} from '../models';

export function BlockFile(arg1:string):Promise<string>;

export function BlockFiles(arg1:Array<string>):Promise<Record<string, string>>;

export function BlockInstalledApp(arg1:apps.InstalledApp):Promise<string>;

export function GetBlockedApps():Promise<Array<firewall.BlockedApp>>;

export function GetInstalledApps():Promise<Array<apps.InstalledApp>>;

export function RefreshApps():Promise<Array<apps.InstalledApp>>;

export function UnblockFile(arg1:string):Promise<string>;

export function UnblockFiles(arg1:Array<string>):Promise<Record<string, string>>;

export function UnblockInstalledApp(arg1:apps.InstalledApp):Promise<string>;
